In [ ]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [4]:
### Load the trained model, scalar pickle, one hot encoding
model = load_model('model.keras')
### Load the encoder and scaler
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder = pickle.load(file)
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

d:\Machine Learning\6. Machine Learning\ANN Project\venv\Lib\site-packages\keras\src\saving\saving_lib.py:843: UserWarning: Skipping variable loading for optimizer 'rm_sprop_2', because it has 8 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [34]:
# Example input data
input_data = {
    'CreditScore' : 600, 
    'Geography' : 'France',
    'Gender' : 'Male', 
    'Age' : 40, 
    'Tenure': 3, 
    'Balance' : 60000, 
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

## Preprocessing
input_df = pd.DataFrame([input_data])

decode_gender = label_encoder_geo.transform([input_df['Gender']])
input_df['Gender'] = int(decode_gender[0])

geo_encoded = onehot_encoder.transform([input_df['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns= onehot_encoder.get_feature_names_out(['Geography']))
input_df = pd.concat([input_df.reset_index(drop=True), geo_encoded_df], axis = 1)  
input_df.drop(['Geography'], axis = 1, inplace = True)
input_df

d:\Machine Learning\6. Machine Learning\ANN Project\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
d:\Machine Learning\6. Machine Learning\ANN Project\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [35]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [36]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [41]:
prediction = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step

In [42]:
prediction

array([[0.04708187]], dtype=float32)

In [43]:
if(prediction[0][0]  > 0.5):
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn